### ISSUE TITLE
Export all the traces to file

### ISSUE THREAD

**Issue by jasond-s** [CtrlSpice/otel-desktop-viewer#145]
The viewer is really handy I love it.

One of the massive perks of having all your traces go to a vendor is the deeper analysis tools that they give you. I am not suggesting this project implements that, but it would be handy to have a simple way of dumping all the traces to a file so that you can analyse the data in other tools. 

Admittedly I could maybe have the collector, or the app for that matter, dump the traces to a file, but I am lazy, and I want a button in a tool. I am running this during benchmarking and property-based testing with generated test input and so I have many traces for the same activity I want to grok.

**Comment by banksean** [comment]
I want this too.  

I hacked up something to do this for my own needs: https://github.com/CtrlSpice/otel-desktop-viewer/pull/155 Saves the in-memory duckdb to disk so you can query it using duckdb cli, or whatever other tools can read those files.

Kudos to @CtrlSpice for integrating duckdb already! - The first thing I thought when I initially tried this viewer out was "omg I want duckdb support so I can run aggregate queries on this trace data" so I was very happy to see it's already in there - opens up a ton of new possibilities.

**Comment by CtrlSpice** [comment]
Hey @banksean I just wanted to thank you for the contribution! The only reason I didn't merge it directly is because I am very not on top of things lately, and was a ways into trying to implement the same thing before I saw the PR 😅 but it was really helpful and got me unblocked. Thank you so much!

Hopefully I can pester my partner into reviewing my code so the feature can go in tonight!
